### ISSUE TITLE
ESP32 with SPIFFSLogger

### ISSUE THREAD

**Issue by hmsilva-br** [bitmario/SPIFFSLogger#4]
Hi,

At first, congratularions for your code!

I tried to compite it to ESP32 and got an error at this line in SPIFFSLogger: "Dir logDir = SPIFFS.openDir(this->_directory);" as it was not declared.
Doing some search in your library, it seams there is no "Dir class declared" when it comes to ESP32 SPIFFS. 
Unfortunately, I am not an expert (problably just a newbie) in C++ to handle with this.

Is there a version, or even an idea, to make it work for ESP32 too? It would be great if so.

I would appreciate some help about it.

**Comment by bitmario** [comment]
Sorry, this has been sitting here for a while...

I don't own an ESP32 and don't really have much time to investigate this. But you are welcome to send a PR to add support for ESP32 as long as it maintains compatibility with ESP8266.
